In [1]:
# Import dependencies

import pandas as pd

import matplotlib as plt

import numpy as np

In [2]:
# Create a set of random latitude and longitude combinations.

lats = np.random.uniform(low=-90.000, high=90.000, size = 1500)

lngs = np.random.uniform(low=-90.000, high=90.000, size = 1500)

lat_lngs = zip(lats, lngs)

lat_lngs

In [3]:
# Add the latitudes and longitudes to a list.

coordinates = list(lat_lngs)
coordinates

[(-76.22600586454286, -10.910890149871605),
 (1.6930085612355583, 7.737807018302192),
 (75.22527975042746, -5.5668083476818),
 (64.0925612919107, 25.898528423203388),
 (-45.65520094416174, 12.481917241332098),
 (-24.639949228885882, 57.525936810233986),
 (76.8303892409476, 87.87116623264498),
 (26.446342093403814, 49.82625386813311),
 (-48.595248978753006, 63.5368137878437),
 (3.978980000792035, 55.955220726662645),
 (-52.20073309755397, 14.894107188459259),
 (-74.34194468324202, 42.043852822106174),
 (88.56223765964083, 63.72154511006437),
 (-77.00694833893147, -77.31838473883394),
 (-27.765421791813374, 13.781464664911482),
 (3.85176399711726, 60.94163540130171),
 (-33.304280551055285, 83.78258079223832),
 (-75.08368533970187, -22.575519046661867),
 (-13.891106064829188, -25.67774361557599),
 (82.75705203060807, 53.97657587831796),
 (-54.302027394599314, -21.247678569263968),
 (37.72656982930161, 48.75746293258146),
 (-23.99424589303706, 33.05625199851599),
 (8.861536609263695, 63.78261870811653),
 (68.84268869749926, -74.23356833194325),
 (-50.93842923045617, -12.448307546249922),
 (-56.464522027667556, -68.28538366039828),
 (19.838116057503896, 43.556559779522985),
 (35.117726653070974, 27.12945552662555),
 (72.51395585170624, -16.37134240987683),
 (-8.278572071324902, 3.31692041408337),
 (-72.72816716742435, -47.24800072348489),
 (53.763219329499236, 64.47555437126792),
 (21.181173632674216, -19.84305964618885),
 (-5.933124002031079, -19.07102547083724),
 (69.04895598892432, -59.658291865547135),
 (13.342465649455903, 0.8483450982777327),
 (-69.7804617081265, 26.874292603681937),
 (75.26447665378879, -37.305681573456944),
 (-71.0208750570005, -48.72860031509671),
 (-1.1812634129484962, 87.18498490045965),
 (42.309995492468886, 30.467616307722196),
 (-26.857496282957413, 48.8183964888253),
 (-51.58085581972233, -27.39782666315454),
 (-57.192736599744876, -60.90342693318971),
 (-79.50653773314751, -82.32041059331183),
 (40.97825159507926, -63.44397593597018),
 (86.62402208201374, -33.25634383300691),
 (-26.71673531177563, 73.77020459732813),
 (-8.727613065738694, 50.46618205262567),
 (-7.969682206086389, 69.91811215702913),
 (63.37173766153995, -17.10160635550814),
 (87.53645717601594, 26.171418443385747),
 (29.265379399489404, 7.142003296228623),
 (57.9760603050012, -67.43085789720702),
 (-82.42106957272345, -9.576129141784108),
 (-25.10023704086646, 40.71120829557458),
 (-38.968244021578776, -53.53128815178427),
 (19.910734918579095, -89.43405131232223),
 (-80.60433144864315, -47.07850037752688),
 (-54.46925588917222, -42.51576817513425),
 (-47.643540680434775, -13.236318048182198),
 (73.1465182236374, -88.22443125603719),
 (68.18320427189596, 19.122359813538694),
 (48.166504526926985, -54.368275759113224),
 (-51.31587761678826, 84.14706898407019),
 (-64.76386068185013, 57.011317473233674),
 (29.392999119782417, -70.94725152706962),
 (-71.82797743169121, 55.21741782357543),
 (-42.27290056049873, -52.28636172612352),
 (41.33514316798917, -40.408644107067616),
 (-3.154623786274257, -28.720440977092665),
 (42.97235678547705, -66.52973650855637),
 (-25.380647407814536, 72.46688061733764),
 (67.72956009591698, 31.000683428262093),
 (-39.70506987435013, 56.319799312549435),
 (-68.53660242948915, -46.63039804776264),
 (4.230823001124605, -85.58549144346428),
 (26.36489094168192, -51.18593921417223),
 (-58.72934336789565, -71.0443732466531),
 (-72.79018003868416, 7.887474272558052),
 (-15.150121608530242, 21.30353062594881),
 (-43.62548070544518, 16.566664536478825),
 (-36.848043112185934, 19.018737000684837),
 (56.169070939752544, 11.533154262015373),
 (-25.175442969652153, -7.780151820579775),
 (-20.00931321039998, 30.767744274569182),
 (-43.956610441333794, 84.46851765195726),
 (75.59089103378321, -68.26288487030646),
 (78.38656615062214, 33.43476552533521),
 (73.02294490307617, 50.808611977378234),
 (-59.9547545256292, -6.986232110715292),
 (87.4001023568826, 66.33483245356774),
 (11.916085128194922, -86.85518729026792),
 (-47.679158516906284, 72.35928043224771),
 (-14.357408521346315, 53.980711939033654),
 (32.33253424439337, -52.81404467320549),
 (-16.424811393223052, 23.109932889943266),
 (60.642090056771366, -32.79529172849939),
 (-60.33004103032161, 53.98200682239349),
 (-12.644171003483493, -32.94089351677422),
 (69.12426971544568, 12.606450031912686),
 (85.36796821144148, 56.62311786236708),
 (85.87169532808366, -13.88297359161443),
 (26.27882998024444, 43.42466379058425),
 (-19.913641066336297, 71.44003598971699),
 (-82.45969838069155, 15.923974657499102),
 (-67.7430570130889, -47.18797219928787),
 (-88.20216468993834, 46.872972814912885),
 (54.658990575748305, -32.0553822167473),
 (25.830153664060433, 89.22367744323265),
 (-77.34298372624673, 81.08487113055102),
 (55.74404898856682, -82.77265727185281),
 (-59.40413106756664, 63.77415268198146),
 (-88.79793753187123, 49.578213203988156),
 (-14.39358101674216, -69.39034376181972),
 (-86.0920075285349, 7.29950834853976),
 (-0.155620417298735, 48.65981736072703),
 (-66.03858015121806, -79.57760546280849),
 (1.302047674431975, -72.07483589043531),
 (-55.97346808729787, -83.28281065451228),
 (59.69976883240892, 25.357143957077454),
 (30.523631124326783, -78.18811438703752),
 (80.83734387790864, 56.02330070933107),
 (28.459286597465763, 6.566930179503373),
 (-73.18418190460528, -71.07009014342452),
 (69.50954456274516, -7.848233207061696),
 (25.372658422249486, 83.20978679019532),
 (62.70135577888607, -18.46039017233761),
 (-74.18991861461683, -42.43843530890331),
 (-31.27079844839018, 85.80929745832114),
 (-16.32217482865667, 72.77032720310547),
 (60.30260075583914, 71.94621629041629),
 (32.717647237825204, -31.279758089424078),
 (2.2229106332903967, -35.214874767160765),
 (1.7990521526223375, 81.26654005523415),
 (42.932341459688416, -18.257542215240534),
 (33.99641782305801, 31.567403621046637),
 (-78.11310574612988, 0.023466561192890367),
 (17.995800998312575, -57.285220911294985),
 (70.84161884376829, -62.304298500104906),
 (-89.83051335594426, -50.44047540733489),
 (61.7096663500991, 73.0998006902824),
 (-5.533967539145721, -52.597158419326945),
 (-34.919224972788605, 26.354601981500252),
 (48.565282844211595, 72.27787203135006),
 (-33.99037620661416, -52.71232169373915),
 (-27.28431787790874, 59.09135505008459),
 (-39.42038939632512, 28.235064933322136),
 (-10.874705923702308, 86.02812171925925),
 (33.94922103140425, -67.15070457403644),
 (49.29693367103667, -50.24650564208128),
 (22.813204259583344, -40.62692580386238),
 (-32.41881156975209, 77.66592531087565),
 (65.00674179466961, 79.28226989130386),
 (11.244326458279133, 75.44177395260303),
 (-15.932673190796805, -0.41778899649564494),
 (-61.46661255431681, -68.24352831968035),
 (-53.60407983515446, 59.759253816278516),
 (72.7467959790176, -29.460070039453967),
 (-89.06796342847976, -12.127392575441007),
 (-16.378649059529167, -35.08351830729722),
 (-75.24054254820331, 17.274191027939978),
 (29.529812355525237, -31.937302809952882),
 (23.879890453684126, 36.67298962236825),
 (25.397979365688187, -81.88170834279065),
 (-85.53072334815259, -76.67651996504185),
 (69.0511870217322, -50.42567790253909),
 (69.95030205070202, 0.05612058629539263),
 (89.86277615242491, 15.207574516692247),
 (26.07055121149496, -64.13205876128472),
 (-48.97344117671635, -14.01557323088717),
 (21.516330105185418, -21.360587401860116),
 (-24.219188458769324, -42.8297879218817),
 (-60.88024169636032, -35.076905486149734),
 (76.66127708122178, 61.07245468248743),
 (-69.94879176943112, 48.59762866512037),
 (9.139401979389689, -84.16358047522206),
 (-46.377061336765415, 48.740813174190606),
 (-0.7871503973628364, -65.94037775962096),
 (5.828915873389846, 28.896049853411952),
 (4.161103839022928, 40.53320746043943),
 (-31.5833413040422, -56.47320761679636),
 (-59.0600759000356, -76.18519163330645),
 (-89.95563905246912, 20.75437571874835),
 (-67.5091149759549, 0.006060935290975067),
 (-59.23611690790509, -58.495000837030084),
 (83.38556535049756, -88.11712168001353),
 (5.6025280888530915, 12.516210231878944),
 (12.559908052591922, -52.572980018692405),
 (-50.43301842208018, 59.67664516085614),
 (46.013594201593804, 69.45592577569522),
 (-73.28432392460954, -51.47196368440164),
 (-87.15999864259122, 2.956809791319614),
 (74.26303181477559, 76.84343821171262),
 (66.41368027480178, 29.801841949520252),
 (-64.54165771528409, 89.91481422000425),
 (42.08850223137125, 6.930156242275288),
 (39.458126735605305, -29.794314457343866),
 (-70.24719053925179, -89.5507577681983),
 (38.79863363597195, -43.3709552730708),
 (-55.9085431705483, -58.25562380923262),
 (21.331159631398734, -17.163015273309043),
 (7.874664866554241, -61.16972520619313),
 (16.408487932474003, 40.07395494620252),
 (-48.73022034278817, -63.5332385720043),
 (-46.78725778849768, -45.11505837679165),
 (80.13863155583113, -48.87933832655019),
 (-12.443948593083391, 1.7983837485548406),
 (-61.075916161867525, 88.30808162223684),
 (47.220483955124564, 33.3094976452208),
 (-67.92678774191879, -55.50915948921234),
 (32.35278511913744, -26.768216330299296),
 (-65.40525983840934, 60.89196086696967),
 (-24.822928307633305, 26.490975108904365),
 (51.0692894530776, -52.75280973341235),
 (-13.438535598189745, 86.98967263305784),
 (48.34432039806177, 49.08671122233278),
 (62.52914927161905, -3.686506912483921),
 (-66.00955994470287, 81.37186040042434),
 (9.584848359025742, 64.13129563845607),
 (56.40938932610743, 26.777636802107907),
 (85.3963396841568, -63.75600789737189),
 (-58.38191753135846, 30.76020136124731),
 (29.228909018325268, 36.62526118966275),
 (-40.34355341238515, -66.31397356324952),
 (11.42102400206214, 32.52125194280856),
 (-34.61803821406712, 43.77923412701983),
 (56.99051363948445, -69.95160096412764),
 (43.71982106445935, 25.610872982086363),
 (-73.2249601810275, -48.256529578331474),
 (42.71783527968549, -2.6056487327960554),
 (-69.69787343504647, -85.40194148173154),
 (-64.42543276657474, -41.97355763238097),
 (-58.07341551257096, -80.79413123158422),
 (18.966695798358245, -29.52243576624649),
 (30.30587266140371, -4.332384203657526),
 (-41.13021021749879, 29.23346251272426),
 (-65.1988863728418, 21.551663318326746),
 (-60.257482713079796, 63.32034901476237),
 (-83.84505445478072, 65.53026114667111),
 (57.53536391460864, 14.614156092334156),
 (-62.83736058066573, -1.5177996846914539),
 (79.53647662893593, 88.17004786569049),
 (23.53736956864998, -53.78006444382754),
 (51.63462632585876, 71.8064788329228),
 (86.47787737959453, -9.408665397998988),
 (59.351733620063385, 70.87248708620726),
 (6.142434204996022, -8.694710524905659),
 (67.61311756235486, 63.84509558831752),
 (19.359873157935766, 87.4128942336838),
 (-34.97646417625217, -26.813059085311103),
 (-29.45518928223195, 32.32734179753213),
 (46.12778815185388, -71.82098470579714),
 (88.68101202135057, 81.64362527770561),
 (26.41556977099006, -53.97876740946564),
 (-67.96086037217631, -3.753364764435389),
 (-65.78054419255704, 60.8655269447587),
 (89.2762940284137, -82.93840215058243),
 (-54.946581306036556, 79.86720987354838),
 (22.252990641503203, -87.89776490387959),
 (-4.231667992530944, 59.939323238891234),
 (66.79742254830703, -29.544502184079086),
 (-35.93923907490542, -87.53799988484815),
 (77.37358634940071, -47.42912245514055),
 (-56.08826423688899, 36.306266836234144),
 (-51.94360712941352, 34.907652068089064),
 (31.79855263434085, -80.8838252180494),
 (-41.28477539263402, -33.6546718914613),
 (53.82612170492911, -79.6706589284402),
 (75.62051135645402, -43.78086113507561),
 (24.477686537790376, 46.10540357567865),
 (53.78109691096114, 34.07128434433055),
 (-75.98779102194797, 44.30370613414044),
 (4.656300827447794, -63.770861701980195),
 (-78.54030905567073, -75.73987511607346),
 (20.90377020927113, 64.70055809923892),
 (-79.27913333067738, 46.843922281575544),
 (88.64402442919436, -40.975318881652576),
 (26.45422667722555, -20.144975518822193),
 (89.30315536367479, -40.07754157723378),
 (9.930135867427481, -30.011481493602396),
 (6.053706770372628, 58.32101185170163),
 (-81.92503965294314, -16.14821812957554),
 (-23.117471446514628, 3.183796291747484),
 (16.830158549932065, 6.702687298308888),
 (2.4668335767699148, -5.381129612839004),
 (-34.790670234342, -32.8604948212763),
 (41.200332295735706, -2.159423401196662),
 (21.19587631889341, -24.294095745210782),
 (-75.00163261290889, -17.25724498433486),
 (-18.835407782868728, 77.05264486482136),
 (27.91348286682451, 40.785907405685435),
 (60.82730318352171, 34.706173291797015),
 (60.17333555872622, 74.21016620561181),
 (-24.991187016899744, -51.18231245174475),
 (-2.0057307218893214, 50.00938737375688),
 (-50.18903037187106, -8.669466042177802),
 (-51.581097479264585, 16.650699289283665),
 (-15.157752518519075, 62.64857441902163),
 (4.95110510772605, -44.95135892433531),
 (59.11572470033602, 7.284432251534369),
 (-87.01251604324902, 54.74981513426468),
 (19.58670507904536, 0.41762895147017787),
 (-48.42531850911296, 30.292066823349685),
 (-72.27744803684077, 77.9895446767703),
 (-37.36850788931505, 49.65447778321965),
 (-13.638236446773675, 29.450401294323854),
 (-49.797929070807, 64.39777550556056),
 (-40.71543974719582, -52.351997876965996),
 (-67.32045823878867, 32.182818800106475),
 (-22.63541822144157, -4.7922221159981575),
 (-74.62683616742883, -83.62418479867092),
 (-49.36304338355288, -81.78502906517102),
 (23.666849279743616, 74.50579034702741),
 (22.069454794031046, -1.5157603792676042),
 (-70.62637282716408, 61.02741814094159),
 (-74.27835693439764, 50.56167350167436),
 (-2.6522092745795476, -49.57473688007641),
 (-74.20328598985549, -72.91764222898425),
 (-87.28559358630507, -47.083453716805444),
 (79.77064959255353, 21.332674911886784),
 (28.88261503334587, 71.34135809539637),
 (54.11877012840563, 0.4470756613158642),
 (34.706501020592825, -79.56430003740684),
 (56.593410573360984, -27.350557044615634),
 (17.339511992924116, -89.11735516871299),
 (5.04030408929421, 9.127477393584797),
 (-21.757771498463498, -51.46697479171784),
 (-35.141025407101544, -29.59537258946918),
 (64.66972897267479, 44.784004416662924),
 (-52.7509383717445, 75.72017545889466),
 (-78.80184130140685, -84.6613583525855),
 (-32.31738425639429, -72.95173887713767),
 (-63.78355094981278, 6.83169271672628),
 (-64.82418601556964, -41.76355765017925),
 (-73.99447511870284, -60.58506362999358),
 (-57.65578833496382, 87.47159922990087),
 (5.570627229077118, 57.689862954309575),
 (-15.186271582574093, -14.039455911714413),
 (41.34340495901546, 68.24662253858875),
 (61.85264174175066, 45.33682555556399),
 (-44.00368425150198, 72.70522246097087),
 (37.18248412224126, 67.22471923545223),
 (37.54400016002505, -5.958059882803084),
 (60.51933420413283, 64.31166964963191),
 (-27.77091593249466, -32.751916205157734),
 (-75.2033485344181, 45.517788636565456),
 (74.99010106504232, -71.01204456975871),
 (2.904542529932172, 36.22963492144933),
 (11.206987963469743, -3.587599507082217),
 (-74.72767730691098, -28.86632323656086),
 (13.542376339998668, -70.8561102144847),
 (-51.04833725499277, 79.2043265647377),
 (-11.852603330337715, -61.28489194771677),
 (-58.96343626233161, 79.59428381712604),
 (-41.339608987773126, -60.469872217036354),
 (53.33409750508406, 87.023943364009),
 (-11.688472162409823, -1.3340428800583481),
 (-41.67631650553043, -79.33358453508149),
 (-45.899129519527456, 84.7262311911372),
 (-32.02192251089742, -13.385958953927883),
 (-72.49674122705764, 61.58679820117956),
 (23.33206484672843, -80.64176653979938),
 (52.08149945763259, -56.934418009854916),
 (48.880122928699734, 58.01011869334772),
 (-43.93353111711701, 77.27684161428363),
 (46.823454502017285, 79.59271029656239),
 (-45.73376161039444, 36.094489411719934),
 (23.844296485162346, 87.3520154262439),
 (50.27154411464244, 19.771408361621226),
 (50.11765473390895, 16.592035945878465),
 (-63.958490951082524, -89.90373087258928),
 (-0.5653285110021073, -80.29750259171229),
 (-54.787868260204824, 31.936330022351996),
 (89.71736352458541, -64.78216816891721),
 (-73.76465122210482, 18.438891995135847),
 (-81.51542969931624, -86.62864078941077),
 (10.479709468152393, -6.990127203702144),
 (63.68002911052304, -85.05421732725691),
 (49.14911798683238, 32.82811568451635),
 (49.675084326884416, -47.21680196210987),
 (40.2405799529908, -62.95828043544165),
 (7.816996084984922, -21.8032170749527),
 (-29.568817947455848, 49.96400213658711),
 (56.38565779386727, -34.53528450055876),
 (-47.390764817005234, 61.58671551990267),
 (75.67979462935506, -64.50870520978928),
 (-42.32865171700856, 8.558578410588794),
 (-68.21966476467402, -59.1622879077902),
 (-45.95113772204139, -80.12848007017061),
 (-72.22174990032741, -43.81888573021782),
 (53.12637596974042, 53.94438619987383),
 (36.870695961766856, 78.73124086497359),
 (61.47594178046563, 25.40216983703135),
 (-12.853413056666227, 14.121661108139662),
 (-5.062553574523037, -47.50110612264015),
 (-47.33861934068107, 56.27360768228715),
 (79.16913853158462, -67.81521717109203),
 (42.77906186982136, 58.40400579329636),
 (-29.524870845180637, -13.449107999320887),
 (6.347271292965885, 89.7354186445539),
 (30.15863534196781, 13.77769225088089),
 (41.02869878539428, -45.73842238242054),
 (-3.745990894960755, -84.5795342334185),
 (-41.408523367686236, 73.20225454495079),
 (-72.57713719919272, 15.410290457343578),
 (-88.2678227196812, 69.73971480226177),
 (-14.263986682356233, -77.18931273747354),
 (14.571347032642592, 58.066486701619425),
 (61.4391959219125, -60.52193462319392),
 (-10.886349005819312, -26.153710899097483),
 (-50.808479433192964, -11.786211268561033),
 (55.69998825112182, -64.63840878199767),
 (76.62866926333851, -76.7581791751174),
 (7.116818856930024, -25.71268659249715),
 (5.512925881974269, 41.48938091763563),
 (43.38249066323135, 77.94372518220439),
 (47.506955132726375, 46.19164597873316),
 (-12.01783790071228, -17.56800914228431),
 (20.015376258966427, 25.343659398452345),
 (38.53865306779491, 57.48679501526354),
 (-88.58183577326419, 80.91747830429637),
 (-57.156504781529094, 45.850790105540455),
 (22.595134073870227, 18.409440234793436),
 (64.16647300124174, 64.61608045016303),
 (56.45724547746099, 40.23145022975734),
 (-47.664743886760476, 33.76605973564631),
 (-19.032168951096352, -10.320459226030366),
 (-48.70329598117221, -65.00826910859709),
 (44.46877952322953, -78.87328199157167),
 (72.54526543590009, -78.49751818661848),
 (84.91402037758598, 18.70989023567124),
 (-11.491070820946135, -54.25343021822145),
 (41.890933899431474, 19.466919066158923),
 (14.31196041022396, -48.49637630122818),
 (35.049679723920164, 89.16105120311286),
 (-25.01259904356371, 86.89136977930127),
 (-61.07941245359696, 9.150191671671507),
 (-47.198956549815165, 40.27816725537008),
 (12.963661948586633, 69.79789555570758),
 (30.19350843155769, -16.538976068807017),
 (68.77993654331837, 68.09153513492734),
 (53.44465445605161, -49.99878852721833),
 (-79.50376094602403, 32.29305107274986),
 (-40.854868910214556, -8.792367075803995),
 (-21.85899972376974, 39.36810395134384),
 (-77.10322341298522, -44.650805485791935),
 (89.7310387048546, 15.93681031430448),
 (46.31109636399384, -26.21825512721395),
 (56.41668870320882, -81.76819235768303),
 (45.49342431022046, 22.115630823754103),
 (37.45932445961542, -54.93029691363249),
 (68.17808437127852, -10.349306427233927),
 (67.02032479636446, -40.826209367579125),
 (64.92269870683947, -22.95417306607851),
 (61.57238516454754, 3.6635384130093485),
 (18.265059681390824, -31.918132976894626),
 (-9.892786668951572, 30.150140640106713),
 (30.628688381059362, 76.96606970727967),
 (19.85482881103725, -0.6286101151191872),
 (25.464142005843357, -0.8892642417720253),
 (-26.54117187522477, 85.7995041203074),
 (-67.21696407567978, 16.853323578906483),
 (-9.533272668722304, 53.35833325489011),
 (72.99978120679881, 1.6188580544162647),
 (63.3667408089936, -24.682097893367512),
 (-63.75606583996169, 48.231953907860884),
 (-13.55205282901899, 37.87396635842134),
 (64.84326018935471, -27.254046883908565),
 (35.28860604981733, 77.02742943324316),

In [4]:
from citipy import citipy

In [5]:
# Create a list fo holding the cities.

cities = []

# Identify the nearest city for each latitude and longitude combination.

for coordinate in coordinates:
    
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name
    
    # If the city is unique, then we will add it to the cities list.
    
    if city not in cities:
        
        cities.append(city)
        
# Print the city count to confirm sufficient count.

len(cities)

636

In [6]:
# Import the requests library.

import requests

# Import the API key.

from config import weather_api_key

In [7]:
# Import the time library and the datetime module from the datetime library.

import time

from datetime import datetime

In [8]:
# Start URL for Weather Map API Call.

url = "https://api.openweathermap.org/data/2.5/weather?units=Imperal&APPID=" + weather_api_key

In [9]:
# Create and empty list to hold hte weather data.

city_data = []

# Print the beginning of the logging.

print("Beginning Data Retrieval      ")
print("------------------------------")

# Create counters.

record_count = 1
set_count = 1


# Loop through all the cities in the list.

for i, city in enumerate(cities):
    
    
    # Group cities in sets of 50 for logging purposes
    
    if (i % 50 == 0 and i >= 50):
        
        set_count += 1
        
        record_count = 1
        
        time.sleep(60)
        
        
    # Create endpoint URL with each city.
    
    city_url = url + "&q=" + city.replace(" ", "+")
    
    
    # Log the URL, record, and set numbers and the city.
    
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    
    # Add 1 to the record count.
    
    record_count +=1
    
    # Run an API request for each of the cities.
    
    try:
        # Parse out the JSON and retrieve data.
        
        city_weather = requests.get(city_url).json()
        
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S') 

        # Append the City information into city_data list
        city_data.append({"City": city.title(), 
                          "Lat": city_lat, 
                          "Lng": city_lng, 
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})
    
    except:
        print('City not found. Skipping....')
        pass
# Indicate that Data Loading is complete.
                                              
print("------------------------------")
print("Data Retrieval Complete.      ")
print("------------------------------")

Beginning Data Retrieval
------------------------------
Processing Record 1 of Set 1 | cape town
Processing Record 2 of Set 1 | mbini
Processing Record 3 of Set 1 | klaksvik
Processing Record 4 of Set 1 | muhos
Processing Record 5 of Set 1 | hermanus
Processing Record 6 of Set 1 | saint-philippe
Processing Record 7 of Set 1 | talnakh
Processing Record 8 of Set 1 | sayhat
Processing Record 9 of Set 1 | eyl
Processing Record 10 of Set 1 | port alfred
Processing Record 11 of Set 1 | amderma
City not found. Skipping....
Processing Record 12 of Set 1 | ushuaia
Processing Record 13 of Set 1 | luderitz
Processing Record 14 of Set 1 | victoria
Processing Record 15 of Set 1 | bambous virieux
Processing Record 16 of Set 1 | sao jose da coroa grande
Processing Record 17 of Set 1 | belushya guba
City not found. Skipping....
Processing Record 18 of Set 1 | arraial do cabo
Processing Record 19 of Set 1 | talesh
City not found. Skipping....
Processing Record 20 of Set 1 | chokwe
Processing Record 21 of Set 1 | kavaratti
Processing Record 22 of Set 1 | clyde river
Processing Record 23 of Set 1 | abha
Processing Record 24 of Set 1 | karpathos
Processing Record 25 of Set 1 | illoqqortoormiut
City not found. Skipping....
Processing Record 26 of Set 1 | gamba
Processing Record 27 of Set 1 | borovskoy
Processing Record 28 of Set 1 | nouadhibou
Processing Record 29 of Set 1 | georgetown
Processing Record 30 of Set 1 | upernavik
Processing Record 31 of Set 1 | tera
Processing Record 32 of Set 1 | kruisfontein
Processing Record 33 of Set 1 | tasiilaq
Processing Record 34 of Set 1 | hambantota
Processing Record 35 of Set 1 | agva
City not found. Skipping....
Processing Record 36 of Set 1 | taolanaro
City not found. Skipping....
Processing Record 37 of Set 1 | cidreira
Processing Record 38 of Set 1 | liverpool
Processing Record 39 of Set 1 | ambilobe
Processing Record 40 of Set 1 | hithadhoo
Processing Record 41 of Set 1 | hofn
Processing Record 42 of Set 1 | longyearbyen
Processing Record 43 of Set 1 | warqla
City not found. Skipping....
Processing Record 44 of Set 1 | iqaluit
Processing Record 45 of Set 1 | toliary
City not found. Skipping....
Processing Record 46 of Set 1 | mar del plata
Processing Record 47 of Set 1 | tekax
City not found. Skipping....
Processing Record 48 of Set 1 | jamestown
Processing Record 49 of Set 1 | qaanaaq
Processing Record 50 of Set 1 | setermoen
Processing Record 1 of Set 2 | gambo
Processing Record 2 of Set 2 | busselton
Processing Record 3 of Set 2 | cockburn town
Processing Record 4 of Set 2 | east london
Processing Record 5 of Set 2 | ribeira grande
Processing Record 6 of Set 2 | natal
Processing Record 7 of Set 2 | yarmouth
Processing Record 8 of Set 2 | kovdor
Processing Record 9 of Set 2 | burica
City not found. Skipping....
Processing Record 10 of Set 2 | codrington
Processing Record 11 of Set 2 | kalabo
Processing Record 12 of Set 2 | asnaes
Processing Record 13 of Set 2 | masvingo
Processing Record 14 of Set 2 | narsaq
Processing Record 15 of Set 2 | vardo
Processing Record 16 of Set 2 | san rafael del sur
Processing Record 17 of Set 2 | souillac
Processing Record 18 of Set 2 | antalaha
Processing Record 19 of Set 2 | saint george
Processing Record 20 of Set 2 | senanga
Processing Record 21 of Set 2 | maceio
Processing Record 22 of Set 2 | gravdal
Processing Record 23 of Set 2 | buraydah
Processing Record 24 of Set 2 | grand river south east
City not found. Skipping....
Processing Record 25 of Set 2 | bredasdorp
Processing Record 26 of Set 2 | rangpur
Processing Record 27 of Set 2 | attawapiskat
City not found. Skipping....
Processing Record 28 of Set 2 | azangaro
Processing Record 29 of Set 2 | mogadishu
Processing Record 30 of Set 2 | punta arenas
Processing Record 31 of Set 2 | miraflores
Processing Record 32 of Set 2 | valkla
Processing Record 33 of Set 2 | mount pleasant
Processing Record 34 of Set 2 | mughal sarai
Processing Record 35 of Set 2 | vestmannaeyjar
Processing Record 36 of Set 2 | carnarvon
Processing Record 37 of Set 2 | quatre cocos
Processing Record 38 of Set 2 | salym
Processing Record 39 of Set 2 | jardim
Processing Record 40 of Set 2 | matara
Processing Record 41 of Set 2 | vila franca do campo
Processing Record 42 of Set 2 | pafos
Processing Record 43 of Set 2 | saint-francois
Processing Record 44 of Set 2 | pangnirtung
Processing Record 45 of Set 2 | poykovskiy
Processing Record 46 of Set 2 | sao felix do xingu
Processing Record 47 of Set 2 | port elizabeth
Processing Record 48 of Set 2 | atasu
Processing Record 49 of Set 2 | santa vitoria do palmar
Processing Record 50 of Set 2 | hamilton
Processing Record 1 of Set 3 | bonavista
Processing Record 2 of Set 3 | ponta do sol
Processing Record 3 of Set 3 | urengoy
Processing Record 4 of Set 3 | koyilandi
City not found. Skipping....
Processing Record 5 of Set 3 | belmonte
Processing Record 6 of Set 3 | umm lajj
Processing Record 7 of Set 3 | naples
Processing Record 8 of Set 3 | ilulissat
Processing Record 9 of Set 3 | raudeberg
Processing Record 10 of Set 3 | marica
Processing Record 11 of Set 3 | quepos
Processing Record 12 of Set 3 | tsihombe
City not found. Skipping....
Processing Record 13 of Set 3 | santa isabel do rio negro
Processing Record 14 of Set 3 | maridi
Processing Record 15 of Set 3 | mandera
Processing Record 16 of Set 3 | tacuarembo
Processing Record 17 of Set 3 | tibati
Processing Record 18 of Set 3 | bathsheba
Processing Record 19 of Set 3 | zhezkazgan
Processing Record 20 of Set 3 | dikson
Processing Record 21 of Set 3 | kuusamo
Processing Record 22 of Set 3 | sainte-maxime
Processing Record 23 of Set 3 | torbay
Processing Record 24 of Set 3 | upata
Processing Record 25 of Set 3 | ginda
Processing Record 26 of Set 3 | comodoro rivadavia
Processing Record 27 of Set 3 | velyka oleksandrivka
Processing Record 28 of Set 3 | ponta delgada
Processing Record 29 of Set 3 | mmathubudukwane
Processing Record 30 of Set 3 | bengkulu
Processing Record 31 of Set 3 | aleksandrov gay
Processing Record 32 of Set 3 | preili
Processing Record 33 of Set 3 | tabuk
Processing Record 34 of Set 3 | general roca
Processing Record 35 of Set 3 | marabba
Processing Record 36 of Set 3 | pietrosani
Processing Record 37 of Set 3 | vitoria
Processing Record 38 of Set 3 | mrirt
City not found. Skipping....
Processing Record 39 of Set 3 | nassjo
Processing Record 40 of Set 3 | zholymbet
Processing Record 41 of Set 3 | toulepleu
City not found. Skipping....
Processing Record 42 of Set 3 | promyshlennyy
Processing Record 43 of Set 3 | paradwip
City not found. Skipping....
Processing Record 44 of Set 3 | richards bay
Processing Record 45 of Set 3 | princeville
Processing Record 46 of Set 3 | mahebourg
Processing Record 47 of Set 3 | panaba
Processing Record 48 of Set 3 | olafsvik
Processing Record 49 of Set 3 | lebu
Processing Record 50 of Set 3 | wilmington island
Processing Record 1 of Set 4 | laguna
Processing Record 2 of Set 4 | moose factory
Processing Record 3 of Set 4 | riyadh
Processing Record 4 of Set 4 | bytosh
Processing Record 5 of Set 4 | ciudad bolivar
Processing Record 6 of Set 4 | keti bandar
Processing Record 7 of Set 4 | los llanos de aridane
Processing Record 8 of Set 4 | sao filipe
Processing Record 9 of Set 4 | bandarbeyla
Processing Record 10 of Set 4 | henties bay
Processing Record 11 of Set 4 | agadez
Processing Record 12 of Set 4 | sassandra
Processing Record 13 of Set 4 | calatayud
Processing Record 14 of Set 4 | sakakah
Processing Record 15 of Set 4 | podporozhye
Processing Record 16 of Set 4 | lokosovo
Processing Record 17 of Set 4 | prudentopolis
Processing Record 18 of Set 4 | grand gaube
Processing Record 19 of Set 4 | salinopolis
Processing Record 20 of Set 4 | tonstad
Processing Record 21 of Set 4 | tessalit
Processing Record 22 of Set 4 | mkushi
Processing Record 23 of Set 4 | coihaique
Processing Record 24 of Set 4 | banswara
Processing Record 25 of Set 4 | taoudenni
Processing Record 26 of Set 4 | mocajuba
Processing Record 27 of Set 4 | ahmadpur east
Processing Record 28 of Set 4 | bridlington
Processing Record 29 of Set 4 | laurinburg
Processing Record 30 of Set 4 | grindavik
Processing Record 31 of Set 4 | san ignacio
Processing Record 32 of Set 4 | kumba

Processing Record 33 of Set 4 | dracena
Processing Record 34 of Set 4 | karpogory
Processing Record 35 of Set 4 | valparaiso
Processing Record 36 of Set 4 | chardara
Processing Record 37 of Set 4 | dvinskoy
Processing Record 38 of Set 4 | termiz
Processing Record 39 of Set 4 | la rinconada
Processing Record 40 of Set 4 | uray
Processing Record 41 of Set 4 | sao joao da barra
Processing Record 42 of Set 4 | lodwar
Processing Record 43 of Set 4 | hounde
Processing Record 44 of Set 4 | oranjestad
Processing Record 45 of Set 4 | pimenta bueno
Processing Record 46 of Set 4 | viedma
Processing Record 47 of Set 4 | kuzedeyevo
Processing Record 48 of Set 4 | ancud
Processing Record 49 of Set 4 | corralillo
Processing Record 50 of Set 4 | saint anthony
Processing Record 1 of Set 5 | emba
Processing Record 2 of Set 5 | ayagoz
Processing Record 3 of Set 5 | bakreswar
Processing Record 4 of Set 5 | wolbrom
Processing Record 5 of Set 5 | jablonne nad orlici
Processing Record 6 of Set 5 | bahia de caraquez
Processing Record 7 of Set 5 | tingrela
City not found. Skipping....
Processing Record 8 of Set 5 | chyhyryn
Processing Record 9 of Set 5 | bubaque
Processing Record 10 of Set 5 | castro
Processing Record 11 of Set 5 | pleshanovo
Processing Record 12 of Set 5 | shache
Processing Record 13 of Set 5 | hollola
Processing Record 14 of Set 5 | catumbela
Processing Record 15 of Set 5 | sitio novo do tocantins
Processing Record 16 of Set 5 | kegayli
City not found. Skipping....
Processing Record 17 of Set 5 | sabang
Processing Record 18 of Set 5 | mizdah
Processing Record 19 of Set 5 | el alto
Processing Record 20 of Set 5 | pisco
Processing Record 21 of Set 5 | salalah
Processing Record 22 of Set 5 | olinda
Processing Record 23 of Set 5 | havre-saint-pierre
Processing Record 24 of Set 5 | esik
Processing Record 25 of Set 5 | nikolskoye
Processing Record 26 of Set 5 | kutum
Processing Record 27 of Set 5 | baherden
Processing Record 28 of Set 5 | faya
Processing Record 29 of Set 5 | igrim
Processing Record 30 of Set 5 | gavrilov posad
Processing Record 31 of Set 5 | fenelon falls
Processing Record 32 of Set 5 | alta floresta
Processing Record 33 of Set 5 | shengjin
Processing Record 34 of Set 5 | sinnamary
Processing Record 35 of Set 5 | lasa
Processing Record 36 of Set 5 | tacoronte
Processing Record 37 of Set 5 | aksarka
Processing Record 38 of Set 5 | inhambane
Processing Record 39 of Set 5 | lagoa
Processing Record 40 of Set 5 | copacele
Processing Record 41 of Set 5 | saint-pierre
Processing Record 42 of Set 5 | stykkisholmur
Processing Record 43 of Set 5 | floro
Processing Record 44 of Set 5 | luwingu
Processing Record 45 of Set 5 | pinjaur
Processing Record 46 of Set 5 | adrar
Processing Record 47 of Set 5 | roald
Processing Record 48 of Set 5 | montepuez
Processing Record 49 of Set 5 | kargil
Processing Record 50 of Set 5 | surgut
Processing Record 1 of Set 6 | husavik
Processing Record 2 of Set 6 | nanortalik
Processing Record 3 of Set 6 | paoua
Processing Record 4 of Set 6 | nesebar
Processing Record 5 of Set 6 | concordia
Processing Record 6 of Set 6 | chuy
Processing Record 7 of Set 6 | coquimbo
Processing Record 8 of Set 6 | bouna
Processing Record 9 of Set 6 | toamasina
Processing Record 10 of Set 6 | namibe
Processing Record 11 of Set 6 | sudbury
Processing Record 12 of Set 6 | villarrica
Processing Record 13 of Set 6 | dingle
Processing Record 14 of Set 6 | alibag
Processing Record 15 of Set 6 | tulum
Processing Record 16 of Set 6 | dolores
Processing Record 17 of Set 6 | rio pomba
Processing Record 18 of Set 6 | turkistan
Processing Record 19 of Set 6 | guane
Processing Record 20 of Set 6 | bonthe
Processing Record 21 of Set 6 | eyrarbakki
Processing Record 22 of Set 6 | port-gentil
Processing Record 23 of Set 6 | sambava
Processing Record 24 of Set 6 | massena
Processing Record 25 of Set 6 | saint-joseph
Processing Record 26 of Set 6 | sic
Processing Record 27 of Set 6 | saint-ambroise
Processing Record 28 of Set 6 | marsa matruh
Processing Record 29 of Set 6 | umm kaddadah
Processing Record 30 of Set 6 | rio gallegos
Processing Record 31 of Set 6 | stornoway
Processing Record 32 of Set 6 | waddan
Processing Record 33 of Set 6 | cayenne
Processing Record 34 of Set 6 | burgos
Processing Record 35 of Set 6 | zapolyarnyy
Processing Record 36 of Set 6 | denizli
Processing Record 37 of Set 6 | soddy-daisy
Processing Record 38 of Set 6 | walvis bay
Processing Record 39 of Set 6 | mansehra
Processing Record 40 of Set 6 | zdunska wola
Processing Record 41 of Set 6 | am timan
Processing Record 42 of Set 6 | karakendzha
City not found. Skipping....
Processing Record 43 of Set 6 | akdepe
Processing Record 44 of Set 6 | luanda
Processing Record 45 of Set 6 | bilma
Processing Record 46 of Set 6 | kostino
Processing Record 47 of Set 6 | barentsburg
City not found. Skipping....
Processing Record 48 of Set 6 | wukari
Processing Record 49 of Set 6 | penzance
Processing Record 50 of Set 6 | buncrana
Processing Record 1 of Set 7 | ugoofaaru
Processing Record 2 of Set 7 | najran
Processing Record 3 of Set 7 | uwayl
City not found. Skipping....
Processing Record 4 of Set 7 | algiers
Processing Record 5 of Set 7 | la rioja
Processing Record 6 of Set 7 | phalaborwa
Processing Record 7 of Set 7 | kabwe
Processing Record 8 of Set 7 | santa rosa
Processing Record 9 of Set 7 | michigan city
Processing Record 10 of Set 7 | arlit
Processing Record 11 of Set 7 | nantucket
Processing Record 12 of Set 7 | san carlos de bariloche
Processing Record 13 of Set 7 | gangapur
Processing Record 14 of Set 7 | saldanha
Processing Record 15 of Set 7 | thilogne
City not found. Skipping....
Processing Record 16 of Set 7 | saint-augustin
Processing Record 17 of Set 7 | kataysk
Processing Record 18 of Set 7 | cheuskiny
City not found. Skipping....
Processing Record 19 of Set 7 | villa carlos paz
Processing Record 20 of Set 7 | batticaloa
Processing Record 21 of Set 7 | marcona
City not found. Skipping....
Processing Record 22 of Set 7 | iquitos
Processing Record 23 of Set 7 | inhambupe
Processing Record 24 of Set 7 | ilo
Processing Record 25 of Set 7 | kabare
Processing Record 26 of Set 7 | wazzan
City not found. Skipping....
Processing Record 27 of Set 7 | muisne
Processing Record 28 of Set 7 | chake chake
Processing Record 29 of Set 7 | ormara
Processing Record 30 of Set 7 | manali
Processing Record 31 of Set 7 | matameye
City not found. Skipping....
Processing Record 32 of Set 7 | sur
Processing Record 33 of Set 7 | puerto colombia
Processing Record 34 of Set 7 | samoded
Processing Record 35 of Set 7 | taltal
Processing Record 36 of Set 7 | bindura
Processing Record 37 of Set 7 | levashi
Processing Record 38 of Set 7 | oranjemund
Processing Record 39 of Set 7 | ischia
Processing Record 40 of Set 7 | mumford
Processing Record 41 of Set 7 | brae
Processing Record 42 of Set 7 | nicoya
Processing Record 43 of Set 7 | bur gabo
City not found. Skipping....
Processing Record 44 of Set 7 | bafq
Processing Record 45 of Set 7 | storsteinnes
Processing Record 46 of Set 7 | jimma
Processing Record 47 of Set 7 | hobyo
Processing Record 48 of Set 7 | koygorodok
Processing Record 49 of Set 7 | kamenka
Processing Record 50 of Set 7 | matay
Processing Record 1 of Set 8 | uniao da victoria
City not found. Skipping....
Processing Record 2 of Set 8 | sault sainte marie
Processing Record 3 of Set 8 | talcahuano
Processing Record 4 of Set 8 | nikel
Processing Record 5 of Set 8 | touros
Processing Record 6 of Set 8 | nueva loja
Processing Record 7 of Set 8 | benjamin aceval
Processing Record 8 of Set 8 | maniitsoq
Processing Record 9 of Set 8 | saint pete beach
Processing Record 10 of Set 8 | black river
Processing Record 11 of Set 8 | vestmanna
Processing Record 12 of Set 8 | quelimane
Processing Record 13 of Set 8 | tumannyy
City not found. Skipping....
Processing Record 14 of Set 8 | thessalon
Processing Record 15 of Set 8 | itarema
Processing Record 16 of Set 8 | maputo
Processing Record 17 of Set 8 | aswan
Processing Record 18 of Set 8 | marawi
Processing Record 19 of Set 8 | point pedro
Processing Record 20 of Set 8 | kuche
City not found. Skipping....
Processing Record 21 of Set 8 | araouane
Processing Record 22 of Set 8 | new amsterdam

Processing Record 23 of Set 8 | yuty
Processing Record 24 of Set 8 | aiquile
Processing Record 25 of Set 8 | monrovia
Processing Record 26 of Set 8 | san andres
Processing Record 27 of Set 8 | mecca
Processing Record 28 of Set 8 | louis trichardt
Processing Record 29 of Set 8 | buenos aires
Processing Record 30 of Set 8 | netivot
Processing Record 31 of Set 8 | altamira
Processing Record 32 of Set 8 | berlevag
Processing Record 33 of Set 8 | goundi
Processing Record 34 of Set 8 | timra
Processing Record 35 of Set 8 | muros
Processing Record 36 of Set 8 | korla
Processing Record 37 of Set 8 | jaguaruna
Processing Record 38 of Set 8 | obo
Processing Record 39 of Set 8 | shelburne
Processing Record 40 of Set 8 | sisimiut
Processing Record 41 of Set 8 | ostrovnoy
Processing Record 42 of Set 8 | corrientes
Processing Record 43 of Set 8 | tiruvottiyur
City not found. Skipping....
Processing Record 44 of Set 8 | omboue
Processing Record 45 of Set 8 | itacare
Processing Record 46 of Set 8 | caluquembe
Processing Record 47 of Set 8 | rocha
Processing Record 48 of Set 8 | bat khela
Processing Record 49 of Set 8 | yar-sale
Processing Record 50 of Set 8 | ngama
Processing Record 1 of Set 9 | scunthorpe
Processing Record 2 of Set 9 | thompson
Processing Record 3 of Set 9 | dhidhdhoo
Processing Record 4 of Set 9 | onda
Processing Record 5 of Set 9 | rundu
Processing Record 6 of Set 9 | jaciara
Processing Record 7 of Set 9 | thunder bay
Processing Record 8 of Set 9 | nizhniy odes
Processing Record 9 of Set 9 | vangaindrano
Processing Record 10 of Set 9 | harrisonburg
Processing Record 11 of Set 9 | bud
Processing Record 12 of Set 9 | kantabanji
Processing Record 13 of Set 9 | caravelas
Processing Record 14 of Set 9 | san rafael
Processing Record 15 of Set 9 | manta
Processing Record 16 of Set 9 | chapais
Processing Record 17 of Set 9 | rawson
Processing Record 18 of Set 9 | algete
Processing Record 19 of Set 9 | beoumi
Processing Record 20 of Set 9 | neuquen
Processing Record 21 of Set 9 | miastko
Processing Record 22 of Set 9 | bella union
Processing Record 23 of Set 9 | plettenberg bay
Processing Record 24 of Set 9 | molina
Processing Record 25 of Set 9 | bodden town
Processing Record 26 of Set 9 | marovoay
Processing Record 27 of Set 9 | abu samrah
Processing Record 28 of Set 9 | salinas
Processing Record 29 of Set 9 | umuarama
Processing Record 30 of Set 9 | luziania
Processing Record 31 of Set 9 | rudbar
Processing Record 32 of Set 9 | port blair
Processing Record 33 of Set 9 | rustenburg
Processing Record 34 of Set 9 | gumdag
Processing Record 35 of Set 9 | nuuk
Processing Record 36 of Set 9 | saalfelden
City not found. Skipping....
Processing Record 37 of Set 9 | illela
Processing Record 38 of Set 9 | kuhdasht
Processing Record 39 of Set 9 | road town
Processing Record 40 of Set 9 | pokhara
Processing Record 41 of Set 9 | puerto varas
Processing Record 42 of Set 9 | krasnoselkup
Processing Record 43 of Set 9 | abu kamal
Processing Record 44 of Set 9 | kudahuvadhoo
Processing Record 45 of Set 9 | dzhusaly
City not found. Skipping....
Processing Record 46 of Set 9 | mosquera
Processing Record 47 of Set 9 | muyezerskiy
Processing Record 48 of Set 9 | sinjar
Processing Record 49 of Set 9 | sindal
Processing Record 50 of Set 9 | deh rawud
City not found. Skipping....
Processing Record 1 of Set 10 | santa elena
Processing Record 2 of Set 10 | arenillas
Processing Record 3 of Set 10 | januaria
Processing Record 4 of Set 10 | laguna de duero
Processing Record 5 of Set 10 | asfi
Processing Record 6 of Set 10 | leh
Processing Record 7 of Set 10 | diego de almagro
Processing Record 8 of Set 10 | umba
Processing Record 9 of Set 10 | montes claros
Processing Record 10 of Set 10 | umzimvubu
City not found. Skipping....
Processing Record 11 of Set 10 | port stanley
Processing Record 12 of Set 10 | awjilah
Processing Record 13 of Set 10 | usvyaty
Processing Record 14 of Set 10 | colares
Processing Record 15 of Set 10 | uyuni
Processing Record 16 of Set 10 | esil
Processing Record 17 of Set 10 | kabelvag
Processing Record 18 of Set 10 | impfondo
Processing Record 19 of Set 10 | kemi
Processing Record 20 of Set 10 | bonoua
Processing Record 21 of Set 10 | saint-georges
Processing Record 22 of Set 10 | progreso
Processing Record 23 of Set 10 | mitsamiouli
Processing Record 24 of Set 10 | oktyabrskoye
Processing Record 25 of Set 10 | margate
Processing Record 26 of Set 10 | abnub
Processing Record 27 of Set 10 | macroom
Processing Record 28 of Set 10 | den helder
Processing Record 29 of Set 10 | alakurtti
Processing Record 30 of Set 10 | bara
Processing Record 31 of Set 10 | mahibadhoo
Processing Record 32 of Set 10 | iskateley
Processing Record 33 of Set 10 | kampene
Processing Record 34 of Set 10 | zangakatun
Processing Record 35 of Set 10 | bhuj
Processing Record 36 of Set 10 | aiken
Processing Record 37 of Set 10 | suez
Processing Record 38 of Set 10 | sorvag
City not found. Skipping....
Processing Record 39 of Set 10 | ogaminana
Processing Record 40 of Set 10 | kyzyl-suu
Processing Record 41 of Set 10 | timmins
Processing Record 42 of Set 10 | aktash
Processing Record 43 of Set 10 | visby
Processing Record 44 of Set 10 | svetlogorsk
Processing Record 45 of Set 10 | litoral del san juan
City not found. Skipping....
Processing Record 46 of Set 10 | urdzhar
City not found. Skipping....
Processing Record 47 of Set 10 | dolbeau
City not found. Skipping....
Processing Record 48 of Set 10 | muzhi
Processing Record 49 of Set 10 | koslan
Processing Record 50 of Set 10 | paragominas
Processing Record 1 of Set 11 | altay
Processing Record 2 of Set 11 | makhinjauri
Processing Record 3 of Set 11 | espanola
Processing Record 4 of Set 11 | farsala
Processing Record 5 of Set 11 | kaka
Processing Record 6 of Set 11 | sao raimundo das mangabeiras
Processing Record 7 of Set 11 | yining
Processing Record 8 of Set 11 | pudozh
Processing Record 9 of Set 11 | katrineholm
Processing Record 10 of Set 11 | kokino
Processing Record 11 of Set 11 | axim
Processing Record 12 of Set 11 | moyale
Processing Record 13 of Set 11 | uchiza
Processing Record 14 of Set 11 | ornskoldsvik
Processing Record 15 of Set 11 | concarneau
Processing Record 16 of Set 11 | cotonou
Processing Record 17 of Set 11 | cayambe
Processing Record 18 of Set 11 | amapa
Processing Record 19 of Set 11 | cascais
Processing Record 20 of Set 11 | almenara
Processing Record 21 of Set 11 | giovinazzo
Processing Record 22 of Set 11 | requena
Processing Record 23 of Set 11 | dhoraji
Processing Record 24 of Set 11 | soloneshnoye
Processing Record 25 of Set 11 | vredendal
Processing Record 26 of Set 11 | chhabra
Processing Record 27 of Set 11 | guia de isora
Processing Record 28 of Set 11 | santa maria
Processing Record 29 of Set 11 | florianopolis
Processing Record 30 of Set 11 | nynashamn
Processing Record 31 of Set 11 | jalu
Processing Record 32 of Set 11 | atar
Processing Record 33 of Set 11 | benguela
Processing Record 34 of Set 11 | raga
Processing Record 35 of Set 11 | humaita
Processing Record 36 of Set 11 | leshukonskoye
Processing Record 37 of Set 11 | doctor pedro p. pena
City not found. Skipping....
Processing Record 38 of Set 11 | floriano
Processing Record 39 of Set 11 | lima
Processing Record 40 of Set 11 | springbok
Processing Record 41 of Set 11 | oriximina
Processing Record 42 of Set 11 | maldonado
Processing Record 43 of Set 11 | mayumba
Processing Record 44 of Set 11 | cacoal
Processing Record 45 of Set 11 | caloto
Processing Record 46 of Set 11 | the valley
Processing Record 47 of Set 11 | guaimaro
Processing Record 48 of Set 11 | kollam
Processing Record 49 of Set 11 | sheregesh
Processing Record 50 of Set 11 | mednogorsk
Processing Record 1 of Set 12 | paamiut
Processing Record 2 of Set 12 | fuengirola
Processing Record 3 of Set 12 | cabo rojo
Processing Record 4 of Set 12 | urumqi
Processing Record 5 of Set 12 | tucuman
Processing Record 6 of Set 12 | mehamn
Processing Record 7 of Set 12 | cochrane
Processing Record 8 of Set 12 | haverfordwest
Processing Record 9 of Set 12 | copiapo
Processing Record 10 of Set 12 | dudinka
Processing Record 11 of Set 12 | iquique
Processing Record 12 of Set 12 | takoradi
Processing Record 13 of Set 12 | inta

Processing Record 14 of Set 12 | conde
Processing Record 15 of Set 12 | jacksonville beach
Processing Record 16 of Set 12 | wyszkow
Processing Record 17 of Set 12 | coulihaut
City not found. Skipping....
Processing Record 18 of Set 12 | tabas
Processing Record 19 of Set 12 | tevriz
Processing Record 20 of Set 12 | peniche
Processing Record 21 of Set 12 | louisbourg
City not found. Skipping....
Processing Record 22 of Set 12 | balkhash
Processing Record 23 of Set 12 | qaqortoq
Processing Record 24 of Set 12 | cabinda
Processing Record 25 of Set 12 | mutsamudu
City not found. Skipping....
Processing Record 26 of Set 12 | aizkraukle
Processing Record 27 of Set 12 | paysandu
Processing Record 28 of Set 12 | sedniv
Processing Record 29 of Set 12 | dagda
Processing Record 30 of Set 12 | tabou
Processing Record 31 of Set 12 | gimbi
Processing Record 32 of Set 12 | sioux lookout
Processing Record 33 of Set 12 | san cristobal
Processing Record 34 of Set 12 | tarudant
City not found. Skipping....
Processing Record 35 of Set 12 | boa vista
Processing Record 36 of Set 12 | morristown
Processing Record 37 of Set 12 | novopistsovo
Processing Record 38 of Set 12 | urucara
Processing Record 39 of Set 12 | japura
Processing Record 40 of Set 12 | aktas
Processing Record 41 of Set 12 | miranorte
City not found. Skipping....
Processing Record 42 of Set 12 | callaway
Processing Record 43 of Set 12 | bayan
Processing Record 44 of Set 12 | makeni
Processing Record 45 of Set 12 | san juan de los morros
Processing Record 46 of Set 12 | sanchursk
Processing Record 47 of Set 12 | sucua
Processing Record 48 of Set 12 | gouda
Processing Record 49 of Set 12 | troina
Processing Record 50 of Set 12 | barranca
Processing Record 1 of Set 13 | coxim
Processing Record 2 of Set 13 | bella vista
Processing Record 3 of Set 13 | rudraprayag
Processing Record 4 of Set 13 | pauini
Processing Record 5 of Set 13 | tigre
Processing Record 6 of Set 13 | warmbad
Processing Record 7 of Set 13 | hargeysa
Processing Record 8 of Set 13 | la roche-sur-yon
Processing Record 9 of Set 13 | sistranda
Processing Record 10 of Set 13 | tubuala
Processing Record 11 of Set 13 | shubarshi
Processing Record 12 of Set 13 | gaeta
Processing Record 13 of Set 13 | manono
Processing Record 14 of Set 13 | zorritos
Processing Record 15 of Set 13 | aasiaat
Processing Record 16 of Set 13 | gamboula
Processing Record 17 of Set 13 | brigantine
Processing Record 18 of Set 13 | anloga
Processing Record 19 of Set 13 | thano bula khan
City not found. Skipping....
Processing Record 20 of Set 13 | bhuban
Processing Record 21 of Set 13 | vila velha
Processing Record 22 of Set 13 | puerto leguizamo
Processing Record 23 of Set 13 | alenquer
Processing Record 24 of Set 13 | wajir
Processing Record 25 of Set 13 | crixas
Processing Record 26 of Set 13 | le chambon-feugerolles
Processing Record 27 of Set 13 | perth
Processing Record 28 of Set 13 | bolshegrivskoye
City not found. Skipping....
Processing Record 29 of Set 13 | chesterville
Processing Record 30 of Set 13 | marv dasht
City not found. Skipping....
Processing Record 31 of Set 13 | boende
Processing Record 32 of Set 13 | sokolo
Processing Record 33 of Set 13 | hemsedal
Processing Record 34 of Set 13 | clearwater
Processing Record 35 of Set 13 | carupano
Processing Record 36 of Set 13 | ovalle
------------------------------
Data Retrieval Complete.
------------------------------

In [10]:
len(city_data)

587

In [11]:
# Convert the array of dictionaries to a Pandas DataFrame.

city_data_df = pd.DataFrame(city_data)

city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Cape Town,-33.9258,18.4232,286.08,84,75,0.51,ZA,2022-06-18 19:56:58
1,Mbini,1.5740,9.6134,297.88,82,100,2.69,GQ,2022-06-18 20:01:17
2,Klaksvik,62.2266,-6.5890,282.66,95,100,15.88,FO,2022-06-18 20:01:17
3,Muhos,64.8080,25.9931,285.31,98,100,3.46,FI,2022-06-18 20:01:18
4,Hermanus,-34.4187,19.2345,284.71,76,3,6.40,ZA,2022-06-18 19:56:59
5,Saint-Philippe,-21.3585,55.7679,292.92,81,68,3.71,RE,2022-06-18 19:53:48
6,Talnakh,69.4865,88.3972,282.33,57,18,3.79,RU,2022-06-18 20:01:19
7,Sayhat,26.4852,50.0405,306.01,43,3,2.67,SA,2022-06-18 20:01:19
8,Eyl,7.9803,49.8164,299.07,74,100,9.86,SO,2022-06-18 20:01:20
9,Port Alfred,-33.5906,26.8910,289.80,75,100,5.22,ZA,2022-06-18 19:58:14

In [14]:
# Rearrange columns.

new_column_order = ["City", "Country", "Date", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed"]

city_data_df = city_data_df[new_column_order]

city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,Cape Town,ZA,2022-06-18 19:56:58,-33.9258,18.4232,286.08,84,75,0.51
1,Mbini,GQ,2022-06-18 20:01:17,1.5740,9.6134,297.88,82,100,2.69
2,Klaksvik,FO,2022-06-18 20:01:17,62.2266,-6.5890,282.66,95,100,15.88
3,Muhos,FI,2022-06-18 20:01:18,64.8080,25.9931,285.31,98,100,3.46
4,Hermanus,ZA,2022-06-18 19:56:59,-34.4187,19.2345,284.71,76,3,6.40
5,Saint-Philippe,RE,2022-06-18 19:53:48,-21.3585,55.7679,292.92,81,68,3.71
6,Talnakh,RU,2022-06-18 20:01:19,69.4865,88.3972,282.33,57,18,3.79
7,Sayhat,SA,2022-06-18 20:01:19,26.4852,50.0405,306.01,43,3,2.67
8,Eyl,SO,2022-06-18 20:01:20,7.9803,49.8164,299.07,74,100,9.86
9,Port Alfred,ZA,2022-06-18 19:58:14,-33.5906,26.8910,289.80,75,100,5.22

In [15]:
# Create the outpute file (CSV).

output_data_file = "weather_data/cities.csv"

# Export the City_Data into a CSV.

city_data_df.to_csv(output_data_file, index_label="City_ID")